from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import fnmatch
import json


PRIORITY_PATTERNS = (
    "DEEP.md",
    "README*",
    "CONTRIBUTING*",
    "docs/**",
    "arch/**",
    "pyproject.toml",
    "package.json",
    "pytest.ini",
    "Makefile",
)
IGNORE_DIR_NAMES = {".git", "node_modules", ".venv", "venv", "dist", "build", ".next"}

START_MARKER = "<!-- deepcode:init:start -->"
END_MARKER = "<!-- deepcode:init:end -->"


@dataclass(frozen=True)
class DeepFileSource:
    relative_path: str
    category: str


@dataclass(frozen=True)
class DiscoveryResult:
    sources: list[DeepFileSource]


@dataclass(frozen=True)
class RefreshResult:
    changed: bool
    source_paths: list[str]
    deep_file_path: Path


def _is_priority_match(relative_path: str) -> bool:
    for pattern in PRIORITY_PATTERNS:
        if fnmatch.fnmatch(relative_path, pattern):
            return True
    return False


def _category(relative_path: str) -> str:
    if relative_path == "DEEP.md":
        return "deep"
    elif relative_path.startswith("README"):
        return "readme"
    elif relative_path.startswith("CONTRIBUTING"):
        return "contributing"
    elif relative_path.startswith("docs/"):
        return "docs"
    elif relative_path.startswith("arch/"):
        return "arch"
    elif relative_path in ("pyproject.toml", "package.json", "pytest.ini", "Makefile"):
        return "config"
    else:
        return "other"


def _priority_key(relative_path: str) -> int:
    if relative_path == "DEEP.md":
        return 0
    elif relative_path.startswith("README"):
        return 1
    elif relative_path.startswith("CONTRIBUTING"):
        return 2
    elif relative_path.startswith("docs/"):
        return 3
    elif relative_path.startswith("arch/"):
        return 4
    elif relative_path in ("pyproject.toml", "package.json", "pytest.ini", "Makefile"):
        return 5
    else:
        return 6


def _render_generated_block(discovery: DiscoveryResult) -> str:
    lines = [
        "# DEEP.md",
        "",
        "This file is generated by Deep Coder's `/init` command.",
        "It provides a concise editing guide for this workspace.",
        "",
        "## Sources",
        "",
    ]
    
    for source in discovery.sources:
        lines.append(f"- `{source.relative_path}` ({source.category})")
    
    lines.extend([
        "",
        "## Human Notes",
        "",
        "Add your project-specific notes, conventions, and reminders below.",
        "This section is preserved across `/init` refreshes.",
        "",
    ])
    
    return "\n".join(lines)


def _merge_generated_block(existing_content: str, generated_block: str) -> str:
    if not existing_content.strip():
        return f"{START_MARKER}\n{generated_block}\n{END_MARKER}\n"
    
    start_idx = existing_content.find(START_MARKER)
    end_idx = existing_content.find(END_MARKER)
    
    if start_idx == -1 or end_idx == -1:
        return f"{START_MARKER}\n{generated_block}\n{END_MARKER}\n\n{existing_content}"
    
    end_idx += len(END_MARKER)
    
    before = existing_content[:start_idx]
    after = existing_content[end_idx:]
    
    return f"{before}{START_MARKER}\n{generated_block}\n{END_MARKER}{after}"


class DeepFileService:
    def __init__(self, *, workspace: Path, state_dir: Path):
        self.workspace = Path(workspace).resolve()
        self.state_dir = Path(state_dir)

    def discover_sources(self) -> DiscoveryResult:
        discovered: list[DeepFileSource] = []
        for path in sorted(self.workspace.rglob("*")):
            if path.is_dir() and path.name in IGNORE_DIR_NAMES:
                continue
            if not path.is_file():
                continue
            rel = path.relative_to(self.workspace).as_posix()
            if _is_priority_match(rel):
                discovered.append(DeepFileSource(relative_path=rel, category=_category(rel)))
        discovered.sort(key=lambda source: _priority_key(source.relative_path))
        return DiscoveryResult(sources=discovered)

    def refresh(self) -> RefreshResult:
        discovery = self.discover_sources()
        rendered_block = _render_generated_block(discovery)
        deep_file_path = self.workspace / "DEEP.md"
        existing = deep_file_path.read_text() if deep_file_path.exists() else ""
        updated = _merge_generated_block(existing, rendered_block)
        deep_file_path.write_text(updated)
        self._write_state(discovery.sources, deep_file_path)
        return RefreshResult(
            changed=updated != existing,
            source_paths=[source.relative_path for source in discovery.sources],
            deep_file_path=deep_file_path,
        )

    def _write_state(self, sources: list[DeepFileSource], deep_file_path: Path) -> None:
        state_path = self.state_dir / "deep" / "init-state.json"
        state_path.parent.mkdir(parents=True, exist_ok=True)
        state_path.write_text(
            json.dumps(
                {
                    "last_refreshed_at": datetime.now(timezone.utc).isoformat(),
                    "workspace_path": str(self.workspace),
                    "deep_file_path": str(deep_file_path),
                    "sources": [source.relative_path for source in sources],
                },
                indent=2,
            )
        )